templateVersion: 1.0.0
defaultVersion: 10.6.1
documentation: https://docs.directus.io/getting-started/introduction.html
type: directus-postgresql
name: Directus
subname: (PostgreSQL)
description: >-
 Directus is a free and open-source headless CMS framework for managing custom
 SQL-based databases.
labels:
 - CMS
 - headless
services:
 $$id:
  name: Directus
  depends_on:
   - $$id-postgresql
   - $$id-redis
  image: directus/directus:$$core_version
  volumes:
   - $$id-uploads:/directus/uploads
   - $$id-database:/directus/database
   - $$id-extensions:/directus/extensions
  environment:
   - KEY=$$secret_key
   - SECRET=$$secret_secret
   - DB_CLIENT=pg
   - DB_CONNECTION_STRING=$$secret_db_connection_string
   - CACHE_ENABLED=true
   - CACHE_STORE=redis
   - REDIS=$$secret_cache_redis
   - ADMIN_EMAIL=$$config_admin_email
   - ADMIN_PASSWORD=$$secret_admin_password
   - CACHE_AUTO_PURGE=true
   - PUBLIC_URL=$$config_public_url
  ports:
   - '8055'
 $$id-postgresql:
  name: Directus PostgreSQL
  depends_on: []
  image: postgres:14-alpine
  volumes:
   - $$id-postgresql-data:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=$$config_postgres_user
   - POSTGRES_PASSWORD=$$secret_postgres_password
   - POSTGRES_DB=$$config_postgres_db
  ports: []
 $$id-redis:
  name: Directus Redis
  depends_on: []
  image: redis:7.0.4-alpine
  command: '--maxmemory 512mb --maxmemory-policy allkeys-lru --maxmemory-samples 5'
  volumes:
   - $$id-redis:/data
  environment: []
variables:
 - id: $$config_public_url
   name: PUBLIC_URL
   label: Public URL
   defaultValue: $$generate_fqdn
   description: ''
 - id: $$secret_db_connection_string
   name: DB_CONNECTION_STRING
   label: Directus Database Url
   defaultValue: >-
    postgresql://$$config_postgres_user:$$secret_postgres_password@$$id-postgresql:5432/$$config_postgres_db
   description: ''
 - id: $$config_postgres_db
   main: $$id-postgresql
   name: POSTGRES_DB
   label: Database
   defaultValue: directus
   description: ''
 - id: $$config_postgres_user
   main: $$id-postgresql
   name: POSTGRES_USER
   label: User
   defaultValue: $$generate_username
   description: ''
 - id: $$secret_postgres_password
   main: $$id-postgresql
   name: POSTGRES_PASSWORD
   label: Password
   defaultValue: $$generate_password
   description: ''
   showOnConfiguration: true
 - id: $$secret_cache_redis
   name: CACHE_REDIS
   label: Redis Url
   defaultValue: redis://$$id-redis:6379
   description: ''
 - id: $$config_admin_email
   name: ADMIN_EMAIL
   label: Initial Admin Email
   defaultValue: admin@example.com
   description: >-
    The email address of the first user that is automatically created. You can
    change it later in Directus.
 - id: $$secret_admin_password
   name: ADMIN_PASSWORD
   label: Initial Admin Password
   defaultValue: $$generate_password
   description: The password of the first user that is automatically created.
   showOnConfiguration: true
 - id: $$secret_key
   name: KEY
   label: Key
   defaultValue: $$generate_password
   description: Unique identifier for the project.
   showOnConfiguration: true
 - id: $$secret_secret
   name: SECRET
   label: Secret
   defaultValue: $$generate_password
   description: Secret string for the project.
   showOnConfiguration: true
